#### 2. Print the numpy version and the configuration 

In [1]:
import numpy as np
print(np.__version__)

1.24.3


In [2]:
print(np.show_config())

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/gabb_/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/gabb_/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/gabb_/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/gabb_/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/gabb_/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/gabb_/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/gabb_/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/gabb_/anaconda3\\Lib

#### 3. Create a null vector of size 10

In [3]:
def null_array(n):

    x = np.zeros(n)

    return x

In [4]:
null_array(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
array_10=np.zeros(10)
print(array_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array

In [8]:
size_in_bytes = array_10.nbytes
size_in_bytes


80

In [ ]:
# a.nbytes = 1000: gives size of the numerical elements: 1000 numerical elements.
# getsizeof(a) = 1128: gives the size of both numerical elements and the reference machinery.
# b.nbtyes: the size of the numerical elements independently of the location of memory (is not affected by the view status of b)
# getsizeof(b) = 128: only calculate the size of the reference machinery, it is afected by the view status..
# getsizeof(b.base) = 1128: This calculate the size of the numerical elements plus the reference machinery independently of the view status.

In [33]:
np.size(array_10)

10

In [34]:
np.shape(array_10)

(10,)

In [35]:
np.ndim(array_10)

1

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
# numpy. add() returns the sum of the two arrays. The return type is either ndarray or scalar , depending on the input type.
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [15]:
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [17]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
array_vector=np.arange(10,49)
array_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
np.flip(array_vector)

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [26]:
my_matrix_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_matrix_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
array_1_10=np.arange(1,10)
array_1_10
array_1_10.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [38]:
array_indexes=np.array([1,2,0,0,4,0])
np.where(array_indexes!= 0)[0]



array([0, 1, 4], dtype=int64)