#### 2. Print the numpy version and the configuration 

In [1]:
import numpy as np
print(np.__version__)

1.24.3


In [2]:
print(np.show_config())

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/gabb_/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/gabb_/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/gabb_/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/gabb_/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/gabb_/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/gabb_/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/gabb_/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/gabb_/anaconda3\\Lib

#### 3. Create a null vector of size 10

In [3]:
def null_array(n):

    x = np.zeros(n)

    return x

In [4]:
null_array(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
array_10=np.zeros(10)
print(array_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array

In [8]:
size_in_bytes = array_10.nbytes
size_in_bytes


80

In [ ]:
# a.nbytes = 1000: gives size of the numerical elements: 1000 numerical elements.
# getsizeof(a) = 1128: gives the size of both numerical elements and the reference machinery.
# b.nbtyes: the size of the numerical elements independently of the location of memory (is not affected by the view status of b)
# getsizeof(b) = 128: only calculate the size of the reference machinery, it is afected by the view status..
# getsizeof(b.base) = 1128: This calculate the size of the numerical elements plus the reference machinery independently of the view status.

In [33]:
np.size(array_10)

10

In [34]:
np.shape(array_10)

(10,)

In [35]:
np.ndim(array_10)

1

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
# numpy. add() returns the sum of the two arrays. The return type is either ndarray or scalar , depending on the input type.
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [15]:
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [17]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
array_vector=np.arange(10,49)
array_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
np.flip(array_vector)

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [26]:
my_matrix_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_matrix_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
array_1_10=np.arange(1,10)
array_1_10
array_1_10.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [40]:
array_indexes=np.array([1,2,0,0,4,0])
np.where(array_indexes!= 0)[0]



array([0, 1, 4], dtype=int64)

#### 11. Create a 3x3 identity matrix 

In [41]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [46]:
np.random.random((3,3,3))

array([[[0.3098846 , 0.67886831, 0.55808888],
        [0.94917659, 0.72947532, 0.485019  ],
        [0.90691811, 0.44188025, 0.52548974]],

       [[0.24949782, 0.47965793, 0.47856038],
        [0.343279  , 0.71148353, 0.51073213],
        [0.8093438 , 0.09368703, 0.94469688]],

       [[0.58489032, 0.63717034, 0.70253738],
        [0.53445275, 0.21241414, 0.97877524],
        [0.25281123, 0.93547334, 0.76048303]]])

In [48]:
np.random.random(((3,3,3)))

array([[[0.19152984, 0.61841637, 0.09877033],
        [0.17246854, 0.77427117, 0.23145707],
        [0.61434551, 0.49903302, 0.63923144]],

       [[0.62995748, 0.7399812 , 0.48900281],
        [0.18006637, 0.85818042, 0.32811724],
        [0.58784242, 0.52701535, 0.45224692]],

       [[0.51027115, 0.86563646, 0.96078288],
        [0.10225813, 0.71383723, 0.79964854],
        [0.68714747, 0.9283795 , 0.79418336]]])

### why does it work with different number of parenthesis?

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [61]:
array_max_min=np.random.random((10,10))
array_max_min

array([[0.40792748, 0.49968455, 0.25800866, 0.46039049, 0.21122342,
        0.29162155, 0.52286625, 0.94808217, 0.56839698, 0.6450469 ],
       [0.18563056, 0.2503926 , 0.42280672, 0.6200251 , 0.00577852,
        0.35481859, 0.85707972, 0.73160718, 0.63813489, 0.10016027],
       [0.98251825, 0.97437042, 0.13121028, 0.53389721, 0.87823827,
        0.87059015, 0.72325968, 0.68201052, 0.71136126, 0.52314052],
       [0.21728869, 0.11962204, 0.58825311, 0.47884261, 0.02265261,
        0.62918584, 0.60696972, 0.14904581, 0.14856874, 0.4773505 ],
       [0.58462475, 0.78279191, 0.1037192 , 0.99701491, 0.35308439,
        0.5276319 , 0.87525352, 0.89475811, 0.17620176, 0.29634161],
       [0.8798272 , 0.92215316, 0.62587397, 0.41346676, 0.25890665,
        0.23860633, 0.50283452, 0.54976001, 0.07358496, 0.66727056],
       [0.85630024, 0.05372276, 0.63709147, 0.46343511, 0.88217803,
        0.33171902, 0.75714314, 0.09480299, 0.68810234, 0.10304697],
       [0.99513731, 0.01411152, 0.4143475

In [53]:
np.min(array_max_min)

0.0058230662857895465

In [54]:
np.max(array_max_min)

0.9989298739202296

In [64]:
# trying with integer random numbers
np.random.randn(10,10)

array([[ 7.64237721e-01,  1.97307605e+00,  1.20067784e+00,
         1.69483259e+00,  1.80594308e-01, -4.21451511e-01,
         6.14971929e-01,  5.66834541e-01,  4.46405263e-01,
         1.15379661e+00],
       [-8.16321741e-01,  1.46953113e+00, -6.45130883e-01,
         8.04334566e-01,  5.23280946e-01,  5.20873474e-01,
         9.58702461e-01,  3.17516243e-01,  1.22760340e+00,
        -5.08483265e-01],
       [ 1.03564273e+00, -9.70421249e-01, -2.28129098e-01,
         9.62009097e-01,  2.83380504e-01, -1.92611953e-01,
         1.19364281e-01, -3.37413764e-01, -1.63120446e-01,
        -1.10724489e-01],
       [ 1.49272501e-01,  5.39304077e-01,  4.06057270e-01,
        -1.05769928e+00,  5.11732723e-01,  9.78819506e-01,
        -1.16467635e-01, -1.56157568e+00, -3.85906807e-01,
        -3.02684699e-01],
       [-1.30328899e+00,  9.30247832e-01, -9.98085289e-01,
         5.42706453e-02, -2.15892362e+00, -1.67049339e-01,
        -2.69997103e+00,  6.51933500e-01,  9.81122372e-01,
        -7.

In [77]:
# another try
matrix_random_int=np.random.randint(1,100,(10,10))
matrix_random_int

array([[85, 94,  4, 83, 64, 50, 36, 50, 37, 74],
       [84,  5, 62, 70, 17, 17, 35, 37, 93, 80],
       [18, 71, 54, 16, 85, 28, 40,  7, 25,  8],
       [10, 14, 98, 81, 12, 86, 86, 23, 25, 39],
       [89, 66, 47, 72, 26,  2, 41, 40, 13, 35],
       [28, 71, 71, 92, 80, 69, 48, 77,  2, 61],
       [ 1, 18, 77, 81, 36, 11, 74, 75, 15, 85],
       [66, 12, 73, 47, 14, 78, 93, 91, 28, 73],
       [74, 36, 25, 72, 16, 14, 48, 91, 99, 73],
       [19, 46, 26, 70, 11, 67, 10, 64, 84,  7]])

In [78]:
np.min(matrix_random_int)

1

In [81]:
np.max(matrix_random_int)

99

In [82]:
# find the index of the max and min element in an integer matrix 
np.argmax(matrix_random_int)

88

In [83]:
np.argmin(matrix_random_int)

60

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [4]:
import numpy as np
random_30=np.random.random(30)
random_30


array([0.8898465 , 0.75856538, 0.84137379, 0.09850747, 0.82694833,
       0.59829545, 0.40906481, 0.65566043, 0.16143769, 0.87644442,
       0.03985936, 0.38706787, 0.6090439 , 0.55019992, 0.60642767,
       0.40558868, 0.84258061, 0.24929568, 0.63340421, 0.21651103,
       0.2240166 , 0.93648061, 0.88278386, 0.90553855, 0.94874911,
       0.56562815, 0.19776126, 0.07176821, 0.74771306, 0.58970034])

In [5]:
np.mean(random_30)

0.5575420985850722

In [7]:
#random with int
random_30_int=np.random.randint(1,100,30)
random_30_int

array([57, 57, 59, 71, 99, 44, 50, 45, 79, 26, 24, 52, 83, 31, 60, 18, 93,
       37, 71, 57, 53, 32, 76,  8, 83, 84, 99, 87, 73, 86])

In [8]:
np.mean(random_30_int)

59.8

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [13]:
matrix_border1_inside0=np.ones((5,5))
matrix_border1_inside0[1:-1, 1:-1] = 0
print(matrix_border1_inside0)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [42]:
matrix_ones=np.ones((5,5))
matrix_ones
matrix_ones[0:5,0:1]=0
matrix_ones[0:5,4:5]=0
matrix_ones[:1,1:4]=0
matrix_ones[4:5,1:4]=0


print(matrix_ones)



[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [84]:
# adding one more layer of 0s

matrix_random15=np.random.randint(0,5,(5,5))
matrix_random15

array([[4, 4, 4, 0, 1],
       [0, 4, 4, 4, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 2],
       [1, 0, 2, 4, 3]])

In [85]:
matrix_random15=np.pad(matrix_random15, pad_width=2, mode="constant", constant_values=0)

In [86]:
matrix_random15

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 4, 4, 0, 1, 0, 0],
       [0, 0, 0, 4, 4, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 2, 0, 0],
       [0, 0, 1, 0, 2, 4, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [73]:
# checking the options of the pad function
matrix_random15 = np.pad(matrix_random15, pad_width=1,mode= "maximum")
matrix_random15

array([[4, 2, 4, 4, 3, 4, 4, 2, 4],
       [1, 0, 0, 0, 1, 1, 0, 0, 1],
       [4, 1, 4, 2, 3, 1, 3, 1, 4],
       [4, 2, 4, 2, 2, 3, 4, 2, 4],
       [4, 0, 0, 4, 1, 3, 0, 0, 4],
       [4, 0, 2, 0, 2, 4, 2, 0, 4],
       [4, 1, 4, 3, 3, 4, 1, 1, 4],
       [1, 0, 0, 0, 1, 1, 0, 0, 1],
       [4, 2, 4, 4, 3, 4, 4, 2, 4]])

In [ ]:
#### 17. What is the result of the following expression? (★☆☆)
#```python
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

In [95]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

In [87]:
0 * np.nan

nan

In [88]:
np.nan == np.nan

False

In [89]:
np.inf > np.nan

False

In [90]:
np.nan - np.nan

nan

In [91]:
np.nan in set([np.nan])

True

In [92]:
0.3 == 3 * 0.1

False

In [ ]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 