In [1]:
import numpy as np


In [2]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [3]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.26487588 0.73446927]
 [0.02922647 0.62124786]]


In [4]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


## Exercise 1
Given, there are 5 numbers in the data set: (8, 12, 16, 24, 4). What is the standard deviation? And, what will be the sum of deviations of individual data points from their mean?

In [21]:
my_array=np.array([8, 12, 16, 24, 4])




In [17]:
my_array.min()


4

In [18]:
my_array.max()

24

In [20]:
my_array.mean()

12.8

In [23]:
sum(my_array)/len(my_array)

12.8

In [28]:
sum((my_array-np.mean(my_array))**2)/len(my_array)

47.36

In [29]:
my_array.std()

6.881860213634101

## Exercise 2
If some outliers are introduced to the dataset, what will happen to the Standard Deviation? Will it increase, decrease or remain the same?




In [40]:
my_array_outliers_negative=np.array([8, 12, 16, 24, 4, -55])
my_array_outliers_negative.std()

26.03683288471673

In [41]:
my_array_outliers_positive=np.array([8, 12, 16, 24, 4, 55])
my_array_outliers_positive.std()

16.935334527417982

## Exercise 3 - no Numpy
## Suppose the below positively skewed distribution has a median of 30, which of the following statement is true?
A) Mean is greater than 30
B) Mean is less than 30
C) Mode is greater than 30
D) Mode is less than 30
E) Both A and D
## F) Both B and C

## Exercise 4
Which value can be the possible value for the median of the below distribution?

In [43]:
array_one=np.array([10, 10, 10, 10, 11, 11, 12, 13, 14 ])
array_two=np.array([15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19])
array_three=np.array([20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24])
array_four=np.array([26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29])
array_five=np.array([30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34])
array_six=np.array([35, 35, 35, 37, 37, 37, 37, 39, 39, 39])
array_seven=np.array([40, 40, 43, 43, 44, 44])
array_eight=np.array([46, 46, 46, 47, 49])
array_nine=np.array([52, 53, 54])
